### ISSUE TITLE
我想询问下，代码中是不是没进行对齐操作

### ISSUE THREAD

**Issue by Paidalin** [zouzhen/real_time_face_recognize#3]
aligned = misc.imresize(cropped, (image_size, image_size), interp='bilinear')  
这一步只有缩放图片大小，我也输出了image_tmp（作为测试时的输入部分），我歪的头，并没有矫正

**Comment by zouzhen** [comment]
对的，目前还没有做对其操作，你贴的那个代码，仅仅只是缩放图片的大小，并没有矫正功能，不过这个可以根据你的需要去调整相应的代码，加上去

**Comment by Paidalin** [comment]
> 对的，目前还没有做对其操作，你贴的那个代码，仅仅只是缩放图片的大小，并没有矫正功能，不过这个可以根据你的需要去调整相应的代码，加上去

嗯，好的，那么没有对齐过程的人脸识别，对于准确率的影响是多少呢，有做过相关测试吗

**Comment by navy63** [comment]
太感谢了，终于确认了，我也发现图像有斜的，图像没有进行对齐。
